using System.Data.Common;

namespace Dawaii.Core.Data
{
    public enum DbKind { Sqlite, MySql }

    /// <summary>
    /// Opens connections to the backing database. Two implementations exist behind this one
    /// interface: <see cref="SqliteConnectionFactory"/> (local single file, default) and
    /// <see cref="MySqlConnectionFactory"/> (shared server for 3+ networked devices, V1.2 req 6).
    /// Repositories are written once against <see cref="DbConnection"/> and work with either.
    /// </summary>
    public interface IDbConnectionFactory
    {
        DbKind Kind { get; }

        /// <summary>SQLite database file path (used for file-copy backup); null for MySQL.</summary>
        string SqliteFilePath { get; }

        /// <summary>Full connection string (used by mysqldump for the MySQL backend).</summary>
        string ConnectionString { get; }

        /// <summary>SQL expression that yields the id generated by the previous INSERT on this connection.</summary>
        string LastInsertIdSql { get; }

        /// <summary>Creates a NEW, opened connection (session configured). Caller disposes it.</summary>
        DbConnection OpenConnection();
    }
}
